"use client";

import type { VocReportJson } from "@/lib/ai/vocReport";

interface Props {
    title: string;
    voc: Pick<VocReportJson, "workspaceName" | "periodStart" | "periodEnd" | "generatedAt">;
    generatedBy: string;
    createdAt: string;
}

export default function ReportHeader({ title, voc, generatedBy, createdAt }: Props) {
    const fmt = (d: string) =>
        new Date(d).toLocaleDateString("en-US", { day: "numeric", month: "short", year: "numeric" });

    return (
        <div className="voc-report-header">
            {/* Eyebrow */}
            <div className="voc-report-eyebrow">
                <span className="voc-report-workspace">{voc.workspaceName}</span>
                <span className="voc-report-sep">·</span>
                <span className="voc-report-period">
                    {fmt(voc.periodStart)} – {fmt(voc.periodEnd)}
                </span>
            </div>

            {/* Title */}
            <h1 className="voc-report-title">📄 {title}</h1>

            {/* Meta */}
            <p className="voc-report-meta">
                Voice of Customer Report · Generated by {generatedBy} on {new Date(createdAt).toLocaleDateString()}
            </p>
        </div>
    );
}
